"""empty message

Revision ID: 2f37a0560538
Revises: 5427a18066a8
Create Date: 2021-02-24 12:11:27.740756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f37a0560538'
down_revision = '5427a18066a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('friends', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('unitno', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'unitno')
    op.drop_column('user', 'friends')
    # ### end Alembic commands ###
