"""empty message

Revision ID: 743b187c050e
Revises: 021a07a92cd0
Create Date: 2021-02-17 01:38:22.278030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743b187c050e'
down_revision = '021a07a92cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('bday', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('firstname', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('gender', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('lastname', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('state', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('zipcode', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zipcode')
    op.drop_column('user', 'state')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'city')
    op.drop_column('user', 'bday')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
