"""empty message

Revision ID: 8d6c9725e5f7
Revises: 743b187c050e
Create Date: 2021-02-19 02:32:12.821242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6c9725e5f7'
down_revision = '743b187c050e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitees', sa.String(length=50), nullable=False),
    sa.Column('eventname', sa.String(length=50), nullable=False),
    sa.Column('eventstreetaddress', sa.String(length=50), nullable=False),
    sa.Column('eventunitno', sa.String(length=50), nullable=False),
    sa.Column('eventstate', sa.String(length=50), nullable=False),
    sa.Column('eventcity', sa.String(length=50), nullable=False),
    sa.Column('eventzipcode', sa.String(length=50), nullable=False),
    sa.Column('eventdescription', sa.String(length=50), nullable=False),
    sa.Column('eventstatus', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=50), nullable=False),
    sa.Column('datestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('addresses', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('lat', sa.String(), nullable=True))
    op.add_column('user', sa.Column('lng', sa.String(), nullable=True))
    op.add_column('user', sa.Column('nick_name', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'user', ['nick_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'nick_name')
    op.drop_column('user', 'lng')
    op.drop_column('user', 'lat')
    op.drop_column('user', 'addresses')
    op.drop_table('comment')
    op.drop_table('association')
    op.drop_table('event')
    # ### end Alembic commands ###
